add markdown chunker
supabase/vecs pull request #32
Opened 2023-07-29 21:31 UTC by jbritain

## What kind of change does this PR introduce?

This adds a markdown chunker which allows you to embed a markdown string.

## What is the new behavior?

The markdown string will be split by headings - each heading will start a new chunk. Headings with no space between the hash and the text are not valid.

Additionally, a `max_tokens` parameter can be passed in which sets the maximum number of tokens (words) per chunk. When a line must be split across multiple chunks, the chunker will try to split the line where there are full stops. If a full stop within the chunk limit cannot be found, the line is split at the last token which will fit within the chunk.

## Additional context

#26

2023-07-31 19:57 UTC, olirice requested changes
This is great!

All the plumbing looks good. `split_by_heading` is a little tricky to follow. How about simplifying that to:

```python
import re

regex_pattern = r'^(#{1,6}\s+.+)$'
sections: list[str | Any] = re.split(regex_pattern, markdown, flags=re.MULTILINE)
```
to split on headers (it won't catch the edge cases like you had for level 1 and 2 allowing "=" and "-" underlining but that's okay)

and then splitting on spaces to count tokens to make sure we don't exceed `max_tokens`

```python
from flupy import flu

for section in sections:
    token_chunks = flu(section.split(" ")).chunk(max_tokens)
    for chunk in token_chunks:
        chunk_text = ' '.join(chunk)
        <YIELD>
```
again, that won't handle all the logic you have, like gravitating towards the nearest full sentence, but 5 branches of that logic aren't covered by the test suite so I'd prefer to keep it simple for now and iterate in later versions.

no need to use flupy if you prefer use lists


Nicely done on the added tests 💯

2023-07-31 19:57 UTC, olirice commented on src/vecs/adapter/markdown.py
> +        max_tokens: int = None,
the type here should be `Optional[int]` or your could change `None` to some arbitrarily large value like `1_000_000` to keep the function signature and its body simpler

2023-07-31 19:57 UTC, olirice commented on src/tests/test_adapters.py
> +                    "# heading 1\n## heading 2\n### heading 3\n#### heading 4\n##### heading 5\n###### heading 6",
adding at least 1 section with some words in it here would be a good test for the md parser

2023-08-17 16:15 UTC, olirice commented
lmk when ready for review or if you have Q's on the CI failure for python 3.9

2023-08-19 12:47 UTC, jbritain commented
I do indeed have questions about the CI failure - I have no idea why it is failing, and I don't currently have the workspace setup to test on older versions

2023-08-22 17:35 UTC, olirice approved these changes

2023-08-22 18:22 UTC, merged