feat: add ability to delete by metadata only
supabase/vecs pull request #57
Opened 2023-11-03 16:08 UTC by jeanmaried

## What kind of change does this PR introduce?

Feature

## What is the current behavior?

I need to be able to delete vectors based solely on their metadata but currently the only way to do so is to already have the ids.

## What is the new behavior?

I added 2 methods as suggestions.
Option #1: add a `delete_by_metadata`
Option #2: `delete_vectors` (temporary name) a suggestion for updating the current `delete` function allow optionally passing the ids or metdata (on or the other).

Please let me know which is an acceptable approach and if there are any objections to having this capability.

2023-11-03 19:43 UTC, olirice commented
Deleting by metadata sounds reasonable. I think the right way to approach it would be to overload the existing `delete` method in a backwards compatible way

Something like:

From
```python
def delete(self, ids: Iterable[str]) -> List[str]:
```
To
```python
def delete(self, ids: Optional[Iterable[str]] = None, filters: Optional[Metadata] = None) -> List[str]:
```

where `filters` goes through the same `build_filter` logic as `query`.

2023-11-06 06:57 UTC, jeanmaried commented
@olirice thank you, I updated the method and the docs.

2023-11-06 15:55 UTC, olirice requested changes
This PR introduces some LOC that aren't covered by the test suite. Could you add tests to handle the new uses case? 

These are the uncovered lines:
<img width="943" alt="Screenshot 2023-11-06 at 9 52 02 AM" src="https://github.com/supabase/vecs/assets/12958657/cefc2a3d-6287-4d12-939e-ca3fad2858f4">


<img width="943" alt="Screenshot 2023-11-06 at 9 52 02 AM" src="https://github.com/supabase/vecs/assets/12958657/56798d50-e287-48cc-b421-c72f2b151839">

2023-11-06 15:55 UTC, olirice commented on src/vecs/collection.py
> +            raise VectorDeletionError("Either ids or metadata must be provided.")
`VectorDeletionError` is not defined. Did you intended to add this in `exc.py`?
if so, it should inherit from ArgError to maintain compatibility

2023-11-06 15:55 UTC, olirice commented on src/vecs/collection.py
> +                if ids is not None:
lets move all client side checks outside the database transaction to keep them as fast as possible.
coalescing `None` to an empty list would probably work best for keeping the logic in the db transaction clear

2023-11-06 15:55 UTC, olirice commented on src/vecs/collection.py
> +                if filters is not None:
same here

2023-11-09 16:39 UTC, jeanmaried commented on src/tests/test_collection.py
> +    with pytest.raises(vecs.exc.ArgError):
@olirice I'm a bit stumped on why this test fails. Any ideas? If both ids and filters are not None, I raise an error in the delete function. Any idea if I am missing something here?

2023-11-10 07:08 UTC, jeanmaried commented on src/tests/test_collection.py
> +    with pytest.raises(vecs.exc.ArgError):
Seems to be passing now. Must have been a cache issue.

2023-11-14 22:30 UTC, olirice approved these changes

2023-11-14 22:30 UTC, olirice commented
very nice, thank you!

2023-11-14 22:33 UTC, merged